name: Build and Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: poll-plugin
          path: target/poll.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: poll-plugin
          path: target/

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          gh release create $SHORT_SHA \
            --title "Release $SHORT_SHA" \
            --notes "## Poll Plugin Release
            
            ### Changes
            - Automated release from commit ${{ github.sha }}
            - Built with Java 17
            - Includes all dependencies (shaded JAR)
            
            ### Installation
            1. Download \`poll.jar\`
            2. Place in your \`plugins\` folder
            3. Restart your server" \
            target/poll.jar
